apiVersion: apps/v1
kind: Deployment
metadata:
  name: coderunner-runner-node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: coderunner-runner-node
  template:
    metadata:
      labels:
        app: coderunner-runner-node
    spec:
      containers:
      - name: runner-node
        image: coderunner/runner-node:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DISPATCHER_URL
          value: "http://coderunner-dispatcher"
        - name: LANGUAGE
          value: "javascript"
        resources:
          limits:
            cpu: "250m"
            memory: "256Mi" 