apiVersion: apps/v1
kind: Deployment
metadata:
  name: coderunner-runner-go
spec:
  replicas: 3
  selector:
    matchLabels:
      app: coderunner-runner-go
  template:
    metadata:
      labels:
        app: coderunner-runner-go
    spec:
      containers:
      - name: runner-go
        image: coderunner/runner-go:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DISPATCHER_URL
          value: "http://coderunner-dispatcher"
        - name: LANGUAGE
          value: "go"
        resources:
          limits:
            cpu: "250m"
            memory: "256Mi" 